name: akademi_yanimda
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  youtube_player_flutter: ^8.1.2
  cloud_firestore: ^4.5.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.0.1
  shared_preferences: ^2.1.0
  flutter_riverpod: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/logo.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/
 